fallback = ''

[matching]
'discord' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Insomnia' = ''
'Bitwarden' = ''
'chrome' = ''
'google-chrome' = ''
'/Google Chrome/' = ''
'Chromium' = ''
'Slack' = ''
'code' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'kitty' = ''